pipeline {
    agent any
	stages {
        stage('Build') {
            withMaven {
                sh 'mvn package' 
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true 
            }
        }
    }
}