name: "SAST Analysis Example Action"
author: "Dennis Medeiros"
branding:
   icon: 'shield'
   color: 'green'
   
description: "Receives file and generates output"

inputs:
   name: 
      description: 'Person to greet'
      default: 'World'
      required: true

   filePath: # id of input
      description: "Path to test script"
      default: "target/verademo.war"
      required: true

#steps:
   #    run: echo "Hello ${{ github.event.inputs.name }}"
    
    
   #   outputs:
    # results-file: # id of output
   #   description: "Path to results file"
 
runs:
  using: "composite"
  steps:
     - name: Say Hello
       run: echo "HELLO"
       shell: bash
     
    # - name: whoami
    #   run: whoami
    #   shell: bash
       
   #  - name: Display structure of files
   #    run: ls -R
   #    shell: bash
       
    - run: echo name: ${{ inputs.name }}
      shell: bash
     
    - run: echo file-path: ${{ inputs.filePath }}
      shell: bash
