name: "SAST Analysis Example Action"
author: "Dennis Medeiros"
branding:
   icon: 'shield'
   color: 'green'
   
description: "Receives file and generates output"

inputs:
   name: 
      description: 'Person to greet'
      default: 'World'
      required: true

  file-path: # id of input
      description: "Path to test script"
      default: "target/verademo.war"
      required: true

#steps:
   #    run: echo "Hello ${{ github.event.inputs.name }}"
    
    
   #   outputs:
    # results-file: # id of output
   #   description: "Path to results file"
 
runs:
  using: "composite"
  steps:
     - name: Say Hello
       run: echo "HELLO"
       shell: bash
       
     - name: Display structure of files
       run: ls -R
       shell: bash
       
     - name: whoami
       run: whoami
       shell: bash
       
     - name: input provided
       run: echo "Name: ${{ github.event.inputs.name }}"
       shell: bash
     
    - name:  file-path provided
       run: echo "file-path: ${{ github.event.inputs. file-path }}"
       shell: bash
