name: "SAST Analysis Example Action"
author: "Dennis Medeiros"
branding:
   icon: 'shield'
   color: 'green'
   
description: "Receives file and generates output"

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  octocatEyeColor:
    description: 'Eye color of the Octocats'
    required: true
    default: 'target/verademo.war'
    
   #filePath: # id of input
   #   description: "Path to test script"
  #    default: "target/verademo.war"
  #    required: true

#steps:
   #    run: echo "Hello ${{ github.event.inputs.name }}"
    
    
   #   outputs:
    # results-file: # id of output
   #   description: "Path to results file"
 
runs:
  using: "composite"
  steps:
      - run: echo Hello ${{ inputs.who-to-greet }}.
        shell: bash
      - run: echo Hello ${{ inputs.octocatEyeColor }}.
        shell: bash
        
      - run: echo Hello ${{ secrets.VERACODE_API_ID_TEST }}.
        shell: bash
      
      - run: echo Hello ${{ secrets.VERACODE_API_KEY_TEST }}.
        shell: bash
        
      - name: Say Hello
        run: echo "HELLO"
        shell: bash
     
    # - name: whoami
    #   run: whoami
    #   shell: bash
       
   #  - name: Display structure of files
   #    run: ls -R
   #    shell: bash
       
  
     
   # - run: echo file-path: ${{ inputs.filePath }}
   #   shell: bash
