name: "SAST Analysis Example Action"
author: "Dennis Medeiros"
branding:
   icon: 'shield'
   color: 'green'
   
description: "Receives file and generates output"

#inputs:
#   name: test
#   description: 'Person to greet'
#   default: 'World'
#   required: true

  #file-path: # id of input
  #  description: "Path to test script"
  #  required: true
  #  default: "test-file.js"

#steps:
#    run: echo "Hello ${{ github.event.inputs.name }}"
    
    
 #   outputs:
 # results-file: # id of output
 #   description: "Path to results file"
 
runs:
  using: "composite"
  steps:
    # - name: Download a Build Artifact
    #   uses: actions/download-artifact@v2.0.10
    #   with:
             # Artifact name
    #         name:  my-artifact
             # Destination path
    #         path: # optional

     - name: Say Hello
       run: echo "HELLO"
       shell: bash
       
     - name: Display structure of files
       run: ls -R
       shell: bash
       
     - name: whoami
       run: whoami
       shell: bash
       
     - name: install components
       run: apt-get update
       shell: bash
     
     - name: install curl
       run: apt-get install -y curl
       shell: bash
       
     #- name: Get Veracode Pipeline Scanner
     #  run: curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
     #  shell: bash
 
     #- run: unzip -o pipeline-scan-LATEST.zip

    #- uses: actions/setup-java@v1
    #  with:
    #    java-version: 1.8
    #- run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --file veracode-pipeline-scan-results-to-sarif.zip
    #  continue-on-error: true
    #- uses: actions/upload-artifact@v1
    #  with:
    #    name: ScanResults
    #    path: results.json
    #- name: Convert pipeline scan output to SARIF format
    #  id: convert
    #  uses: veracode/veracode-pipeline-scan-results-to-sarif@master
    #  with:
    #    pipeline-results-json: results.json
    #- uses: github/codeql-action/upload-sarif@v1
    #  with:
    # Path to SARIF file relative to the root of the repository
    #    sarif_file: veracode-results.sarif
