# This basic workflow will run Veracode SAST analysis

name: Manually triggered workflow

on:
workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  SAST-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Send Greeting
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
      - name: Say Goodbye
        run: echo "Goodbye!"
